[phases.setup]
nixPkgs = ["nodejs-18_x", "exiftool", "vips"]

[phases.install]
cmds = [
  "npm ci --only=production --prefer-offline --no-audit",
  "cd client && npm ci --only=production --no-audit"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "mkdir -p server/data",
  "mkdir -p temp",
  "echo 'Build complete - data directories created'"
]

[start]
cmd = "NODE_ENV=production node server/server.js" 