[phases.setup]
nixPkgs = ["nodejs-18_x", "exiftool"]

[phases.install]
cmds = [
  "npm ci --only=production --prefer-offline || npm ci --only=production --no-optional",
  "cd client && npm ci --only=production",
  "cd client && npm run build"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start" 