[phases.setup]
nixPkgs = ["nodejs-18_x", "exiftool"]

[phases.install]
cmds = [
  "npm ci --only=production --prefer-offline || npm ci --only=production --no-optional",
  "cd client && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "echo 'Client build complete'"
]

[start]
cmd = "npm start" 